const groupSel = document.querySelector("#group");
const weekSel  = document.querySelector("#week");
const metaEl   = document.querySelector("#meta");
const tableEl  = document.querySelector("#table");
const refreshBtn = document.querySelector("#refresh");
const exportIcsBtn = document.querySelector("#export-ics");

async function listWeeks() {
  // Look at folders in /data/ (flat list is simplest: maintain a small JSON index committed by the Action)
  // For now, hardcode last few weeks; later replace with /data/index.json generated by the Action.
  return [
    { label: "week 10 (03-NOV-25)", startISO: "2025-11-03" },
    { label: "week 11 (10-NOV-25)", startISO: "2025-11-10" }
  ];
}

function slug(s) { return s.replace(/[^a-z0-9_]+/gi, "_"); }

function renderTable(headers, rows) {
  const table = document.createElement("table");
  table.className = "table";

  const thead = document.createElement("thead");
  const trh = document.createElement("tr");
  headers.forEach(h => { const th = document.createElement("th"); th.textContent = h; trh.appendChild(th); });
  thead.appendChild(trh);

  const tbody = document.createElement("tbody");
  rows.forEach(r => {
    const tr = document.createElement("tr");
    headers.forEach(h => {
      const td = document.createElement("td");
      td.textContent = r[h] || "";
      td.setAttribute("data-label", h);
      tr.appendChild(td);
    });
    tbody.appendChild(tr);
  });

  table.append(thead, tbody);
  tableEl.innerHTML = "";
  tableEl.appendChild(table);
}

function toRows(payload) {
  const headers = ["Day","Start","End","Code","Title","Type","Room","Lecturer"];
  const rows = payload.events.map(e => ({
    "Day": e.day,
    "Start": e.start,
    "End": e.end,
    "Code": e.moduleCode,
    "Title": e.title,
    "Type": e.type,
    "Room": e.room,
    "Lecturer": e.lecturer
  }));
  return { headers, rows };
}

async function load() {
  const group = groupSel.value;
  const week = weekSel.value;      // ISO date string
  const url = `data/${week}/${slug(group)}.json`;
  const res = await fetch(url);
  if (!res.ok) { tableEl.textContent = "No data yet."; metaEl.textContent=""; return; }
  const payload = await res.json();

  metaEl.textContent = `${payload.meta.group} · ${payload.meta.weekLabel}`;
  const { headers, rows } = toRows(payload);
  renderTable(headers, rows);

  exportIcsBtn.onclick = () => downloadICS(payload);
}

function pad(n){ return String(n).padStart(2,"0"); }
function toICSDate(dateISO, timeHHMM) {
  const [y,m,d] = dateISO.split("-").map(Number);
  const [hh,mm] = timeHHMM.split(":").map(Number);
  return `${y}${pad(m)}${pad(d)}T${pad(hh)}${pad(mm)}00`;
}

function icsEscape(s){ return s.replace(/([,;])/g,"\\$1").replace(/\n/g,"\\n"); }

function downloadICS(payload) {
  const lines = [
    "BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//MyTimetable//EN"
  ];
  for (const e of payload.events) {
    const dtStart = toICSDate(e.dateISO, e.start);
    const dtEnd   = toICSDate(e.dateISO, e.end);
    const title = `${e.moduleCode || ""} ${e.title || ""}`.trim();
    const desc = [e.type, e.lecturer].filter(Boolean).join(" · ");
    lines.push(
      "BEGIN:VEVENT",
      `UID:${crypto.randomUUID()}@mytimetable`,
      `DTSTAMP:${toICSDate(payload.meta.weekStartISO, "09:00")}`,
      `DTSTART:${dtStart}`,
      `DTEND:${dtEnd}`,
      `SUMMARY:${icsEscape(title)}`,
      e.room ? `LOCATION:${icsEscape(e.room)}` : "",
      desc ? `DESCRIPTION:${icsEscape(desc)}` : "",
      "END:VEVENT"
    );
  }
  lines.push("END:VCALENDAR");
  const blob = new Blob([lines.filter(Boolean).join("\r\n")], { type: "text/calendar" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${payload.meta.group}-${payload.meta.weekStartISO}.ics`;
  a.click();
  URL.revokeObjectURL(a.href);
}

async function init() {
  const weeks = await listWeeks();
  weekSel.innerHTML = weeks.map(w => `<option value="${w.startISO}">${w.label}</option>`).join("");
  // Preselect latest (last item)
  weekSel.value = weeks.at(-1).startISO;

  weekSel.addEventListener("change", load);
  groupSel.addEventListener("change", load);
  refreshBtn.addEventListener("click", load);
  await load();
}
init();
